name: auto-merge

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-merge:
    uses: mdn/workflows/.github/workflows/auto-merge.yml@main
    with:
      target-repo: "GooborgStudios/mdn-bcd-collector"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
